spring.application.name=gym-application

storage.init.file=data/initial-data.txt
storage.training.types=data/training-types.txt

entityFactoryType=default

spring.datasource.url=jdbc:postgresql://localhost:5432/gymapp
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.generate_statistics=true