spring.application.name=gym-application

storage.init.file=data/initial-data.txt
storage.training.types=data/training-types.txt

spring.datasource.url=jdbc:postgresql://localhost:5432/gymapp
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.generate_statistics=true


management.endpoints.web.exposure.include=health, info, prometheus, metrics, gym-training-stats
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

# Shared JWT secret
jwt.secret=some-secret

management.server.port=8088

logging.file.name=./logs/main-service/gymapp.logs


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Circuit Breaker
resilience4j.circuitbreaker.instances.workloadServiceCircuitBreaker.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.workloadServiceCircuitBreaker.sliding-window-size=2
resilience4j.circuitbreaker.instances.workloadServiceCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.workloadServiceCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.workloadServiceCircuitBreaker.permitted-number-of-calls-in-half-open-state=1

# Logging
logging.pattern.level="%5p [transactionId:%X{transactionId}]"

# Messaging
app.messaging.trainer-workload-queue=trainer-workload-message-queue

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin1

concurrency-level=1-1
